site_name: ddddkw Blog
docs_dir: docs
site_dir: site
site_description: The Blogs record by dkw
site_url: https://mydomain.org/mysite
repo_url: https://github.com/ddddkw/ddddkw.github.io.git
repo_name: ddddkw/ddddkw.github.io.git # 仓库地址
copyright: Copyright &copy; 2024 ddddkw # 左下角的版权声明
# edit_uri: edit/main/docs/ # 开启编辑
nav:
  - 技术:
#    - 主页: index.md
    - 搭建github.Pages: homePage/buildPage.md
    - mkdocs&图片: homePage/pictures.md
  - 开发:
    - 前端:
       - js实现文件排序: technology/web/js实现文件排序.md
       - es6新增知识: technology/web/es6新增知识.md
       - let和var的区别: technology/web/let和var的区别.md
       - echarts饼图镶嵌图片: technology/web/echartsPie.md
       - 默认导出和命名导出: technology/web/默认导出和命名导出.md
       - react:
          - react-router: technology/web/react/router.md
          - antdesign-upload组件的使用以及文件存储展示: technology/web/react/upload.md
          - react中的局部样式: technology/web/react/reactStyle.md
          - redux: technology/web/react/redux.md
       - 低代码平台:
          - first: technology/web/lowCode/first.md
    - 后端:
       - 主页: technology/boot/index.md
       - 记一次大数据量查询时的优化: technology/boot/1.md
    - nginx使用中的405和403: technology/nginx.md
  - 学习:
      - 小记: study/index.md
      - GoogleV8底层原理:
        - 1,V8如何执行一段JavaScript代码: study/GoogleV8/first.md
        - 2,js对象模型全解: study/GoogleV8/second.md
        - 3,V8实现对象继承: study/GoogleV8/third.md
        - 4,V8拆箱装箱机制: study/GoogleV8/four.md
        - 5,基于拆箱装箱的解析: study/GoogleV8/five.md
        - 6,V8中的闭包解析: study/GoogleV8/six.md
        - 7,js中的异步编程以及事件循环机制: study/GoogleV8/seven.md
        - 8,异步编程演变和发布订阅: study/GoogleV8/eight.md
        - 9,Promise与控制反转: study/GoogleV8/nine.md
        - 10,Generator函数与协程原理及实现: study/GoogleV8/ten.md
        - 11,co模块解析以及源码分析: study/GoogleV8/11.md
        - 12,async函数的实现原理: study/GoogleV8/12.md
        - 12,手写Promise A+规范的Promise: study/GoogleV8/13.md
      - 浏览器工作原理:
        - 1,浏览器的工作过程: study/BrowserPrinciple/1.md
        - 2,浏览器中的js的执行机制: study/BrowserPrinciple/2.md
        - 3,为什么JavaScript代码会出现栈溢出: study/BrowserPrinciple/3.md
        - 4,var的缺陷以及let、const: study/BrowserPrinciple/4.md
        - 5,js执行上下文的角度理解this: study/BrowserPrinciple/5.md
        - 6,栈空间和堆空间，数据是如何存储的: study/BrowserPrinciple/6.md
      - webpack原理分析及实践:
        - 1,webpack流程操作: study/Webpack/1.md
        - 2,webpack各版本对比以及性能优化: study/Webpack/2.md
        - 3,webpack实践(1): study/Webpack/3.md
        - 4,webpack实践(2): study/Webpack/4.md
        - 5,性能优化实践: study/Webpack/5.md
        - 6,webpack Terser: study/Webpack/6.md
      - nodejs学习:
        - 1,nodejs的简介: study/nodejs/1.md
        - 2,express中间件的顺序和放行: study/nodejs/2.md
        - 3,nodejs连接MySQL以及ejs模板引擎的使用: study/nodejs/3.md
        - 4,cookie和session: study/nodejs/4.md
      - nginx:
        - 1,反向代理和正向代理: study/nginx/1.md
        - 2,nginx中的accessLog: study/nginx/2.md
        - 3,nginx端的性能优化: study/nginx/3.md
  - 源码:
      - vue: sourceCode/index.md
      - 虚拟DOM: sourceCode/虚拟DOM.md
  - demo:
      - 个人博客: products/blog.md
      - 页面构建: products/build.md
  - 关于:
    - about.md
  - 友链:
    - otherLink.md
theme:
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.footer
    - navigation.tabs
    - navigation.prune
    - navigation.footer
    - content.code.annotate
    - content.code.copy
    - toc.integrate
    - toc.follow
    - search.suggest # 开启搜索建议
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share #搜索分享按钮
    # - header.autohide
    - announce.dismiss
    # - content.action.edit
  #logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    logo: material/dog
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    repo: fontawesome/brands/git-alt    #右上角仓库图标
    edit: material/pencil
    view: material/eye
  name: material
  font:
    text: Roboto Mono
  language: zh
  palette:
    # primary: pink
    # scheme: default
    # accent: indigo
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)" # 日间模式
      scheme: default
      primary: light blue
      accent: pink
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)" # 夜间模式
      scheme: slate
      primary: blue
      accent: pink
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
extra:
  images_dir: assets
  static_dir: assets
  generator: false
  homepage: https://ddddkw.github.io
  # alternate: # 中英文切换
  #   - name: English
  #     link: /en/
  #     lang: en
  #   - name: 中文
  #     link: /zh/
  #     lang: zh
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ddddkw
    - icon: fontawesome/brands/mastodon
      link: https://ddddkw.github.io
  # consent:
  #   title: Cookie consent
  #   description: >-
  #     We use cookies to recognize your repeated visits and preferences, as well
  #     as to measure the effectiveness of our documentation and whether users
  #     find what they're searching for. With your consent, you're helping us to
  #     make our documentation better.
    # cookies:
    #   analytics: Custom name
# Markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
plugins:
#  - blog:
#      blog_dir: .
#      blog_toc: true
#      post_date_format: short
#      # post_url_format: "{date}/{slug}"
#      # post_url_max_categories: 2
#      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
#        kwds:
#          case: lower
  - search
  # - tables
#  - tags:
#      tags_file: tags.md


