site_name: ddddkw Blog
docs_dir: docs
site_dir: site
site_description: The Blogs record by dkw
site_url: https://mydomain.org/mysite
repo_url: https://github.com/ddddkw/ddddkw.github.io.git
repo_name: ddddkw/ddddkw.github.io.git # 仓库地址
copyright: Copyright &copy; 2024 ddddkw # 左下角的版权声明
# edit_uri: edit/main/docs/ # 开启编辑
nav:
  - 技术:
#    - 主页: index.md
    - mkdocs&图片: homePage/pictures.md
    - 搭建github.Pages: homePage/buildPage.md
  - 开发:
    - 前端:
       - js实现文件排序: technology/web/js实现文件排序.md
       - es6新增知识: technology/web/es6新增知识.md
       - let和var的区别: technology/web/let和var的区别.md
       - echarts饼图镶嵌图片: technology/web/echartsPie.md
       - 默认导出和命名导出: technology/web/默认导出和命名导出.md
       - 低代码平台:
          - first: technology/web/lowCode/first.md
    - 后端: technology/boot/index.md
  - 源码:
      - vue: sourceCode/vue.md
  - 关于:
    - about.md
theme:
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.footer
    - navigation.tabs
    - navigation.prune
    - navigation.footer
    - content.code.annotate
    - content.code.copy
    - toc.integrate
    - toc.follow
    - search.suggest # 开启搜索建议
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share #搜索分享按钮
    # - header.autohide
    - announce.dismiss
    # - content.action.edit
  #logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    logo: material/dog
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    repo: fontawesome/brands/git-alt    #右上角仓库图标
    edit: material/pencil
    view: material/eye
  name: material
  font:
    text: Roboto Mono
  language: zh
  palette:
    # primary: pink
    # scheme: default
    # accent: indigo
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)" # 日间模式
      scheme: default
      primary: light blue
      accent: pink
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)" # 夜间模式
      scheme: slate
      primary: blue
      accent: pink
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
extra:
  images_dir: assets
  static_dir: assets
  generator: false
  homepage: https://ddddkw.github.io
  # alternate: # 中英文切换
  #   - name: English
  #     link: /en/
  #     lang: en
  #   - name: 中文
  #     link: /zh/
  #     lang: zh
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ddddkw
    - icon: fontawesome/brands/mastodon
      link: https://ddddkw.github.io
  # consent:
  #   title: Cookie consent
  #   description: >-
  #     We use cookies to recognize your repeated visits and preferences, as well
  #     as to measure the effectiveness of our documentation and whether users
  #     find what they're searching for. With your consent, you're helping us to
  #     make our documentation better.
    # cookies:
    #   analytics: Custom name
# Markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
plugins:
#  - blog:
#      blog_dir: .
#      blog_toc: true
#      post_date_format: short
#      # post_url_format: "{date}/{slug}"
#      # post_url_max_categories: 2
#      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
#        kwds:
#          case: lower
  - search
  # - tables
#  - tags:
#      tags_file: tags.md


